// Code generated by mockery v2.14.1. DO NOT EDIT.

package domain

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockFintechUseCase is an autogenerated mock type for the FintechUseCase type
type MockFintechUseCase struct {
	mock.Mock
}

// AddMoneyUc provides a mock function with given fields: c, to, amount
func (_m *MockFintechUseCase) AddMoneyUc(c *gin.Context, to string, amount int) (Account, error) {
	ret := _m.Called(c, to, amount)

	var r0 Account
	if rf, ok := ret.Get(0).(func(*gin.Context, string, int) Account); ok {
		r0 = rf(c, to, amount)
	} else {
		r0 = ret.Get(0).(Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, string, int) error); ok {
		r1 = rf(c, to, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountUc provides a mock function with given fields: c, userName
func (_m *MockFintechUseCase) GetAccountUc(c *gin.Context, userName string) (Account, error) {
	ret := _m.Called(c, userName)

	var r0 Account
	if rf, ok := ret.Get(0).(func(*gin.Context, string) Account); ok {
		r0 = rf(c, userName)
	} else {
		r0 = ret.Get(0).(Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, string) error); ok {
		r1 = rf(c, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserUc provides a mock function with given fields: c, userName
func (_m *MockFintechUseCase) GetUserUc(c *gin.Context, userName string) (UserType, error) {
	ret := _m.Called(c, userName)

	var r0 UserType
	if rf, ok := ret.Get(0).(func(*gin.Context, string) UserType); ok {
		r0 = rf(c, userName)
	} else {
		r0 = ret.Get(0).(UserType)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, string) error); ok {
		r1 = rf(c, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginUc provides a mock function with given fields: c, userName, password
func (_m *MockFintechUseCase) LoginUc(c *gin.Context, userName string, password string) error {
	ret := _m.Called(c, userName, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gin.Context, string, string) error); ok {
		r0 = rf(c, userName, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterUserUc provides a mock function with given fields: c, userName, email, password
func (_m *MockFintechUseCase) RegisterUserUc(c *gin.Context, userName string, email string, password string) (string, error) {
	ret := _m.Called(c, userName, email, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(*gin.Context, string, string, string) string); ok {
		r0 = rf(c, userName, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, string, string, string) error); ok {
		r1 = rf(c, userName, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveMoneyUc provides a mock function with given fields: c, from, amount
func (_m *MockFintechUseCase) RemoveMoneyUc(c *gin.Context, from string, amount int) (Account, error) {
	ret := _m.Called(c, from, amount)

	var r0 Account
	if rf, ok := ret.Get(0).(func(*gin.Context, string, int) Account); ok {
		r0 = rf(c, from, amount)
	} else {
		r0 = ret.Get(0).(Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, string, int) error); ok {
		r1 = rf(c, from, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferMoneyUc provides a mock function with given fields: c, from, to, amount
func (_m *MockFintechUseCase) TransferMoneyUc(c *gin.Context, from string, to string, amount int) (Account, error) {
	ret := _m.Called(c, from, to, amount)

	var r0 Account
	if rf, ok := ret.Get(0).(func(*gin.Context, string, string, int) Account); ok {
		r0 = rf(c, from, to, amount)
	} else {
		r0 = ret.Get(0).(Account)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gin.Context, string, string, int) error); ok {
		r1 = rf(c, from, to, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockFintechUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockFintechUseCase creates a new instance of MockFintechUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockFintechUseCase(t mockConstructorTestingTNewMockFintechUseCase) *MockFintechUseCase {
	mock := &MockFintechUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
