POST http://localhost:3030/api/register
Content-Type: application/json


{
  "user_name": "juwon",
  "email": "marcus@marcus.com",
  "password": "password123",
  "role": "admin"
}
###
POST http://localhost:5050/api/v1/signin
Content-Type: application/json

{
  "user_name": "marcus",
  "password": "password123"
}
###
POST http://localhost:3030/api/juwon/transfer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1d29uIiwiaXNzIjoidGVzdCIsImV4cCI6MTY2OTYxNTAyMn0.ZNhe8YnYhxsSKr2hGzO-JvLTkiMH2umSzAJMvvbDUqo


{
  "to": "marcus",
  "amount": 70000
}
###
GET http://localhost:3030/api/juwon
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1d29uIiwiaXNzIjoidGVzdCIsImV4cCI6MTY2OTE5NDI3NX0.fk5VoaZNJfPqjU-C9Rjvp-1FpuUxnz4PWqACxCzsWXo


###
GET http://localhost:3030/api/juwon/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1d29uIiwiaXNzIjoidGVzdCIsImV4cCI6MTY2OTYxNTAyMn0.ZNhe8YnYhxsSKr2hGzO-JvLTkiMH2umSzAJMvvbDUqo


###
GET http://localhost:3030/api/swagger/

