version: '2.x'
services:
  fintech-test:
    image: fintech-app-test:test
    ports:
      - "8080:4040"
    environment:
      - PORT=4040
    depends_on:
      - dbnode1
  fintech-prod:
    image: fintech-app:0.0.1
    ports:
      - "8080:4040"
    environment:
      - PORT=4040
      - APP_COUCHBASE_HOST=localhost
      - APP_COUCHBASE_USER=Administrator
      - APP_COUCHBASE_PASSWORD=couchbase
      - APP_COUCHBASE_BUCKET=fintech
    depends_on:
      - dbnode1
  dbnode1:
    image: couchbase/server:7.0.5
    volumes:
      - ./data/couchDB/node1:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
  dbnode2:
    image: couchbase/server:7.0.5
    volumes:
      - ./data/couchDB/node1:/opt/couchbase/var

